<?php

namespace App\Repository;

/**
 * CircularEconomyProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircularEconomyProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
